// processing.js
export const SET_IS_PROCESSING = "SET_IS_PROCESSING";
export const GET_IS_PROCESSING = "GET_IS_PROCESSING";

export const GET_LOGIN_INFO = "GET_LOGIN_INFO";
export const SET_LOGIN_INFO = "SET_LOGIN_INFO";
export const POST_LOGIN = "POST_LOGIN";
export const POST_USER_LOGIN = "POST_USER_LOGIN";

export const REVOKE_AUTHENTICATION = "REVOKE_AUTHENTICATION";

export const GET_ACCOUNT_INFO = "GET_ACCOUNT_INFO";
export const SET_ACCOUNT_INFO = "SET_ACCOUNT_INFO";
export const POST_ACCOUNT = "POST_ACCOUNT";
export const PUT_ACCOUNT = "PUT_ACCOUNT";

export const GET_UNFILTERED_TWEETS_FOR_ADMIN =
  "GET_UNFILTERED_TWEETS_FOR_ADMIN";
export const SET_UNFILTERED_TWEETS_FOR_ADMIN =
  "SET_UNFILTERED_TWEETS_FOR_ADMIN";
export const DELETE_TWEET = "DELETE_TWEET";
export const CANCEL_DELETE = "CANCEL_DELETE";
export const VERIFY_DELETE_TWEET = "VERIFY_DELETE_TWEET";
export const SET_TWEET_ID_TO_DELETE = "SET_TWEET_ID_TO_DELETE";

export const GET_ALL_TWEETS = "GET_ALL_TWEETS";
export const SET_ALL_TWEETS = "SET_ALL_TWEETS";
export const GET_FILLTERED_TWEETS = "GET_FILLTERED_TWEETS";
export const GET_TWEET = "GET_TWEET";
export const SET_TWEET = "SET_TWEET";
export const GET_ONE_USER_TWEETS = "GET_ONE_USER_TWEETS";
export const SET_ONE_USER_TWEETS = "SET_ONE_USER_TWEETS";
export const GET_ONE_USER_REPLIES = "GET_ONE_USER_REPLIES";
export const SET_ONE_USER_REPLIES = "SET_ONE_USER_REPLIES";
export const GET_ONE_USER_LIKES = "GET_ONE_USER_LIKES";
export const SET_ONE_USER_LIKES = "SET_ONE_USER_LIKES";

export const GET_CURRENT_USER = "GET_CURRENT_USER";
export const SET_CURRENT_USER = "SET_CURRENT_USER";

// userProfile.js
export const FETCH_CURRENT_USER = "FETCH_CURRENT_USER";
export const RESET_CURRENT_USER_PROFILE = "RESET_CURRENT_USER_PROFILE";
export const PUT_CURRENT_USER_PROFILE = "PUT_CURRENT_USER_PROFILE";

export const GET_TOP_USERS = "GET_TOP_USERS";
export const SET_TOP_USERS = "SET_TOP_USERS";

// adminUsers.js
export const GET_ALL_USERS = "GET_ALL_USERS";
export const SET_ALL_USERS = "SET_ALL_USERS";

// followship.js
export const GET_CURRENT_USER_FOLLOWERS = "GET_CURRENT_USER_FOLLOWERS";
export const SET_CURRENT_USER_FOLLOWERS = "SET_CURRENT_USER_FOLLOWERS";
export const GET_CURRENT_USER_FOLLOWINGS = "GET_CURRENT_USER_FOLLOWINGS";
export const SET_CURRENT_USER_FOLLOWINGS = "SET_CURRENT_USER_FOLLOWINGS";

// export const GET_FOLLOWERS = "GET_FOLLOWERS";
// export const SET_FOLLOWERS = "SET_FOLLOWERS";
// export const GET_FOLLOWEING = "GET_FOLLOWEING";
// export const SET_FOLLOWEING = "SET_FOLLOWEING";

// 當前使用者追蹤其他人
export const POST_FOLLOWSHIP = "POST_FOLLOWSHIP";
// 當前使用者取消追蹤其他人
export const DELETE_FOLLOWSHIP = "DELETE_FOLLOWSHIP";

// likeship.js
// 對推文新增Like
export const POST_LIKE = "POST_LIKE";

// 對推文刪除Like
export const DELETE_LIKE = "DELETE_LIKE";

export const GET_NOTIFICATION = "GET_NOTIFICATION";
export const IS_NOTIFICATION_OPEN = "IS_NOTIFICATION_OPEN";
export const IS_NOTIFICATION_CONFIRM = "IS_NOTIFICATION_CONFIRM";

export const ADD_NOTIFICATION = "ADD_NOTIFICATION";
export const ADD_NOTIFICATION_CONFIRM = "ADD_NOTIFICATION_CONFIRM";
export const REMOVE_NOTIFICATION = "REMOVE_NOTIFICATION";

export const GET_LATEST_PRIVATE_ROOM_MESSAGES =
  "GET_LATEST_PRIVATE_ROOM_MESSAGES";
export const SET_LATEST_PRIVATE_ROOM_MESSAGES =
  "SET_LATEST_PRIVATE_ROOM_MESSAGES";

// 聊天室私人訊息
export const CLEAR_ONE_ROOM_MESSAGES = "CLEAR_ONE_ROOM_MESSAGES";

// 訂閱社群通知
export const GET_COMMUNITY_NOTIFICATION = "GET_COMMUNITY_NOTIFICATION";
export const SET_PRIVATE_CHAT_NOTIFICATION = "SET_PRIVATE_CHAT_NOTIFICATION";
export const SET_NEW_NOTIFICATION = "SET_NEW_NOTIFICATION";
export const RESET_COMMUNITY_NOTIFICATION = "RESET_COMMUNITY_NOTIFICATION";

// 社群未讀通知
export const GET_COMMUNITY_NOTIFICATION_UNREAD =
  "GET_COMMUNITY_NOTIFICATION_UNREAD";
export const SET_COMMUNITY_NOTIFICATION_UNREAD =
  "SET_COMMUNITY_NOTIFICATION_UNREAD";
export const CLEAR_COMMUNITY_NOTIFICATION_UNREAD =
  "CLEAR_COMMUNITY_NOTIFICATION_UNREAD";
export const INCREMENT_UNREAD_COMMUNITY_NOTIFICATION =
  "INCREMENT_UNREAD_COMMUNITY_NOTIFICATION";
export const INCREMENT_COMMUNITY_NOTIFICATION_UNREAD_PUBLIC_MESSAGE =
  "INCREMENT_COMMUNITY_NOTIFICATION_UNREAD_PUBLIC_MESSAGE";

// 私人聊天室各自的社群各自未讀通知
export const GET_SUM_OF_UNREAD_PRIVATE_MESSAGES =
  "GET_SUM_OF_UNREAD_PRIVATE_MESSAGES";
export const SET_SUM_OF_UNREAD_PRIVATE_MESSAGES =
  "SET_SUM_OF_UNREAD_PRIVATE_MESSAGES";
export const ADD_UNREAD_NOTIFICATION_FOR_ROOM =
  "ADD_UNREAD_NOTIFICATION_FOR_ROOM";
export const CLEAR_UNREAD_FOR_ROOM = "CLEAR_UNREAD_FOR_ROOM";